[package]
name = "dimo-report"
description = "Report templating and PDF rendering of inspection reports."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
dimo-core.workspace = true

[lints]
workspace = true
